blank_issues_enabled: false
contact_links:
  - name: ğŸ“ è³ªå•ãƒ»ç›¸è«‡
    url: https://github.com/discussions
    about: ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆã«å½“ã¦ã¯ã¾ã‚‰ãªã„è³ªå•ã‚„ç›¸è«‡ã¯Discussionsã‚’ã”åˆ©ç”¨ãã ã•ã„
